from django.urls import path

from .views import (
    BrandDetailView,
    BrandListCreateView,
    CategoryDetailView,
    CategoryListCreateView,
    ColorDetailView,
    ColorListCreateView,
    ColorVariantDetailView,
    ColorVariantListCreateView,
    DiscountDetailView,
    DiscountListCreateView,
    FreeItemDetailView,
    FreeItemListCreateView,
    ImageDetailView,
    ImageListCreateView,
    LoginView,
    LogoutView,
    OptionGroupDetailView,
    OptionGroupListCreateView,
    OptionValueDetailView,
    OptionValueListCreateView,
    OrderNotificationView,
    ProductDetailBySlugView,
    ProductListView,
    ProductManageDetailView,
    ProfileView,
    RegisterView,
    ResendOTPView,
    UserDetailView,
    UserListView,
    VerifyEmailOTPView,
    VideoDetailView,
    VideoListCreateView,
)


urlpatterns = [
    path("products/", ProductListView.as_view(), name="product-list"),
    path("products/<slug:slug>/", ProductDetailBySlugView.as_view(), name="product-detail"),
    path("auth/register/", RegisterView.as_view(), name="auth-register"),
    path("auth/login/", LoginView.as_view(), name="auth-login"),
    path("auth/logout/", LogoutView.as_view(), name="auth-logout"),
    path("auth/profile/", ProfileView.as_view(), name="auth-profile"),
    path("auth/verify-email/", VerifyEmailOTPView.as_view(), name="auth-verify-email"),
    path("auth/resend-otp/", ResendOTPView.as_view(), name="auth-resend-otp"),
    path("orders/notify/", OrderNotificationView.as_view(), name="order-notify"),
    path("manage/products/<int:pk>/", ProductManageDetailView.as_view(), name="manage-product-detail"),
    path("manage/categories/", CategoryListCreateView.as_view(), name="manage-category-list"),
    path("manage/categories/<int:pk>/", CategoryDetailView.as_view(), name="manage-category-detail"),
    path("manage/brands/", BrandListCreateView.as_view(), name="manage-brand-list"),
    path("manage/brands/<int:pk>/", BrandDetailView.as_view(), name="manage-brand-detail"),
    path("manage/colors/", ColorListCreateView.as_view(), name="manage-color-list"),
    path("manage/colors/<int:pk>/", ColorDetailView.as_view(), name="manage-color-detail"),
    path("manage/color-variants/", ColorVariantListCreateView.as_view(), name="manage-color-variant-list"),
    path("manage/color-variants/<int:pk>/", ColorVariantDetailView.as_view(), name="manage-color-variant-detail"),
    path("manage/option-groups/", OptionGroupListCreateView.as_view(), name="manage-option-group-list"),
    path("manage/option-groups/<int:pk>/", OptionGroupDetailView.as_view(), name="manage-option-group-detail"),
    path("manage/option-values/", OptionValueListCreateView.as_view(), name="manage-option-value-list"),
    path("manage/option-values/<int:pk>/", OptionValueDetailView.as_view(), name="manage-option-value-detail"),
    path("manage/free-items/", FreeItemListCreateView.as_view(), name="manage-free-item-list"),
    path("manage/free-items/<int:pk>/", FreeItemDetailView.as_view(), name="manage-free-item-detail"),
    path("manage/discounts/", DiscountListCreateView.as_view(), name="manage-discount-list"),
    path("manage/discounts/<int:pk>/", DiscountDetailView.as_view(), name="manage-discount-detail"),
    path("manage/images/", ImageListCreateView.as_view(), name="manage-image-list"),
    path("manage/images/<int:pk>/", ImageDetailView.as_view(), name="manage-image-detail"),
    path("manage/videos/", VideoListCreateView.as_view(), name="manage-video-list"),
    path("manage/videos/<int:pk>/", VideoDetailView.as_view(), name="manage-video-detail"),
    path("manage/users/", UserListView.as_view(), name="manage-user-list"),
    path("manage/users/<int:pk>/", UserDetailView.as_view(), name="manage-user-detail"),
]
